const assert=require('node:assert/strict'), crypto=require('node:crypto'), fs=require('node:fs');
const M=require('../engine.js');
let checks=0;
function test(name,fn){fn();checks++;console.log('PASS '+name);}
function book(){const events=[];return {events,add(kind,data,date='2026-09-01'){const e=M.prepare(events,{id:crypto.randomUUID(),kind,data,date},{today:'2026-10-10',now:'2026-10-10T18:00:00Z'});events.push(e);return e;},state(){return M.state(events);}};}
const b=book();b.add('opening',{amount:10000});
const product=b.add('product',{name:'Rice',cost:100,price:300,openingQty:10}).data.id;
const supplier=b.add('party',{name:'Supplier',type:'supplier'}).data.id;
const customer=b.add('party',{name:'Customer',type:'customer'}).data.id;
b.add('purchase',{partyId:supplier,lines:[{productId:product,qty:10,price:200}],discount:200,paid:0});
const sale=b.add('sale',{partyId:customer,lines:[{productId:product,qty:5,price:300,stockCost:1,costBasis:2}],discount:50,paid:0});
test('discounted purchases feed moving average; credit sales recognize full revenue',()=>{assert.equal(sale.data.lines[0].stockCost,700);assert.equal(b.state().products[product].inventoryValue,2100);const p=M.profit(b.state());assert.equal(p.revenue,1450);assert.equal(p.cost,700);assert.equal(p.net,750);});
test('expense affects profit and cash but no customer or supplier balance',()=>{const before=b.state();b.add('expense',{amount:100,category:'كهرباء ومياه',note:'Electricity'});const after=b.state();assert.equal(M.profit(after).net,650);assert.equal(after.cash,before.cash-100);assert.deepEqual(after.parties,before.parties);});
test('supplier payments and customer receipts do not change profit',()=>{b.add('payment',{partyId:supplier,amount:300});b.add('receipt',{partyId:customer,amount:200});assert.equal(M.profit(b.state()).net,650);});
test('product price edits preserve historic costs and remaining inventory value',()=>{b.add('product',{id:product,name:'Rice',cost:999,price:1200});assert.equal(M.profit(b.state()).cost,700);assert.equal(b.state().products[product].inventoryValue,2100);});
test('legacy invoices reconstruct historical weighted costs without mutating journal',()=>{const events=JSON.parse(JSON.stringify(b.events));const e=events.find(x=>x.id===sale.id);delete e.data.lines[0].stockCost;delete e.data.lines[0].costBasis;const original=JSON.stringify(events);assert.equal(M.profit(M.state(events)).net,650);assert.equal(JSON.stringify(events),original);});
test('later cancellation reverses cost and revenue in cancellation period',()=>{b.add('void',{targetId:sale.id,note:'Cancelled'},'2026-10-01');const s=b.state();assert.equal(M.profit(s,'2026-09-01','2026-09-30').net,650);assert.equal(M.profit(s,'2026-10-01','2026-10-31').net,-750);assert.equal(M.profit(s).net,-100);assert.equal(s.products[product].inventoryValue,2800);});
test('cancel expense refunds cash and reverses profit expense exactly once',()=>{const exp=b.events.find(e=>e.kind==='expense'),before=b.state().cash;b.add('void',{targetId:exp.id,note:'Duplicate'},'2026-10-02');assert.equal(b.state().cash,before+100);assert.equal(M.profit(b.state()).net,0);assert.throws(()=>b.add('void',{targetId:exp.id,note:'Again'}),/غير قابلة/);});
test('expense validates balance, category, note, amount, and forbids party settlement',()=>{for(const data of [{amount:999999,category:'a',note:'a'},{amount:1,note:'a'},{amount:1,category:'a'},{amount:-1,category:'a',note:'a'},{amount:1,category:'a',note:'a',partyId:supplier}])assert.throws(()=>b.add('expense',data));});
test('expense retry reuses same ID and does not double count',()=>{const e=b.events.find(x=>x.kind==='expense');assert.deepEqual(M.prepare(b.events,{id:e.id,kind:e.kind,data:e.data,date:e.date},{today:'2026-10-10'}),e);});
test('empty period and invalid range and old server are explicit',()=>{assert.equal(M.profit(b.state(),'2027-01-01','2027-01-31').net,0);assert.throws(()=>M.profit(b.state(),'2026-10-01','2026-09-01'));assert.throws(()=>M.profit({}),/تحديث/);});
test('fractional quantities and repeated lines exhaust inventory with integer cost',()=>{const c=book(),p=c.add('product',{name:'Fraction',cost:7,price:10,openingQty:1}).data.id;c.add('sale',{lines:[{productId:p,qty:.333,price:10},{productId:p,qty:.333,price:10},{productId:p,qty:.334,price:10}],paid:9});assert.equal(c.state().products[p].inventoryValue,0);assert.equal(M.profit(c.state()).cost,7);});
test('purchase discount allocation reconciles across multiple and repeated products',()=>{const c=book(),p=c.add('product',{name:'A',cost:1,price:5}).data.id,q=c.add('product',{name:'B',cost:1,price:5}).data.id,sp=c.add('party',{name:'S',type:'supplier'}).data.id;c.add('purchase',{partyId:sp,lines:[{productId:p,qty:1,price:3},{productId:q,qty:1,price:3},{productId:p,qty:1,price:3}],discount:2,paid:0});assert.equal(Object.values(c.state().products).reduce((a,p)=>a+p.inventoryValue,0),7);c.add('sale',{lines:[{productId:p,qty:2,price:5},{productId:q,qty:1,price:5}],paid:15});assert.equal(M.profit(c.state()).cost,7);});
test('cancellation cannot predate its original document',()=>{const e=b.add('expense',{amount:1,category:'a',note:'a'},'2026-10-05');assert.throws(()=>b.add('void',{targetId:e.id,note:'a'},'2026-10-01'),/يسبق/);});
test('frontend and backend accounting engines are identical',()=>assert.equal(fs.readFileSync(__dirname+'/../engine.js','utf8'),fs.readFileSync(__dirname+'/../apps-script/Engine.gs','utf8')));
console.log(checks+' profit and expense checks passed.');
